### 모듈 - pickle

In [2]:
import pickle
import pickle
list = ['a', 'b', 'c']
with open('list.txt', 'wb') as f:
    pickle.dump(list, f)

In [4]:
#읽어오기
with open('list.txt', 'rb') as f:
    data = pickle.load(f) # 단 한줄씩 읽어옴

data

['a', 'b', 'c']

In [7]:
#72467314-01 
class Person:
    def hello(self):
        print('class는 처음이지?')
        print(locals())
        print("+++++++++++++++++++++")
        print(globals())
        print("+++++++++++++++++++++")

        
jeeho = Person()
jeeho.hello()

class는 처음이지?
{'self': <__main__.Person object at 0x000001E2B008E708>}
+++++++++++++++++++++
{'__name__': '__main__', '__doc__': 'Automatically created module for IPython interactive environment', '__package__': None, '__loader__': None, '__spec__': None, '__builtin__': <module 'builtins' (built-in)>, '__builtins__': <module 'builtins' (built-in)>, '_ih': ['', 'import pickle', "import pickle\nimport pickle\nlist = ['a', 'b', 'c']\nwith open('list.txt', 'wb') as f:\n    pickle.dump(list, f)", "#읽어오기\nwith open('list.txt', 'rb') as f:\n    data = pickle.load(f) # 단 한줄씩 읽어옴", "#읽어오기\nwith open('list.txt', 'rb') as f:\n    data = pickle.load(f) # 단 한줄씩 읽어옴\n\ndata", '#72467314-01 \nclass Person:\n    def hello(self):\n        print(\'class는 처음이지?\')\n        print(locals())\n        print("+++++++++++++++++++++")\n        print(globals())\n        print("+++++++++++++++++++++")', '#72467314-01 \nclass Person:\n    def hello(self):\n        print(\'class는 처음이지?\')\n        print(locals())\n 

### globals() 테스트

In [9]:
value = 100

globals()['value']

100

In [12]:
def func(x,y):
    return x,y
print(globals()['func'])
print(globals()['func'](3,4))

<function func at 0x000001E2B00B6EE8>
(3, 4)


In [17]:
class Book:
    def __init__(self, name):
        self.name = name
        print(locals())
print(globals()['Book'])
python = globals()['Book']('철저입문')
python.__dict__

<class '__main__.Book'>
{'self': <__main__.Book object at 0x000001E2B00E79C8>, 'name': '철저입문'}


{'name': '철저입문'}

# list copy

In [18]:
names = ['kang', 'hong', 'kim']

print(names)
print(len(names))

['kang', 'hong', 'kim']
3


In [19]:
student_names = names
student_names[0] = 'lee'
print(names) #엥 names까지 바뀌어 버렸다. 

['lee', 'hong', 'kim']


In [20]:
a = 10
b = a
b = 20
print(a,b) #근데 값을 assign했다면 바뀌지 않네요

10 20


In [25]:
a = [10]
def my_fun(a):
    a[0] = a[0] + 10
    print(a) #이건 함수 내의 local변수 아니냐?
    
print(a)
my_fun(a)
print(a)

[10]
[20]
[20]


call by value, call by reference의 느낌. R에서의 local과 global로 이해하면 되지 않을까 싶다.

In [27]:
a = 10
b = a
b = 20
print(a is b)

False


In [28]:
names = ['kang', 'hong', 'kim']
student_names = names
student_names[0] = 'lee'
print(names is student_names) #리스트는 왜 자꾸 같게 나올까?

True


In [31]:
a = [1,2,3]
print(id(a))
a.append(4)
print(id(a))

b = [4,5,6]
print(id(b))
c = a+b
print(id(a), id(b), id(c)) #각자의 id는 다 다르다

2073127975304
2073127975304
2073127558216
2073127975304 2073127558216 2073126714888


In [32]:
arrys = [[1,2,3],[4,5,6],[7,8,9]]
arrys[0]

[1, 2, 3]

In [38]:
list_a = [[10,20], [30,40], [50,60]]
list_b = list_a
list_b[0][0] = 500
print(list_a)
print(list_b)
print(id(list_a))
print(id(list_b))
#리스트의 주소가 같아 버린다. 

[[500, 20], [30, 40], [50, 60]]
[[500, 20], [30, 40], [50, 60]]
2073143107336
2073143107336


### 문제 해결을 위한 copy 모듈의 등장

In [34]:
import copy

In [36]:
list_b = copy.deepcopy(list_a)
list_b[0][1] = 1000
print(list_a)
print(list_b)

[[500, 20], [30, 40], [50, 60]]
[[500, 1000], [30, 40], [50, 60]]


In [37]:
print(id(list_a))
print(id(list_b))
#리스트의 주소는 달라졌다!!

2073144098504
2073144078152


# NumPy 

In [39]:
import numpy as np

### 시퀀스 데이터를 이용한 배열(ndarray) 형성

In [42]:
data1 = [1,2,3,4,5,6]
arr1 = np.array(data1)
print(type(arr1)) #ndarray 라고 하는 구나.
arr1

<class 'numpy.ndarray'>


array([1, 2, 3, 4, 5, 6])

In [43]:
data2 = [[1,2,3], [4,5,6], [7,8,9]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [47]:
data3 = [1, 2.53, 4.65, 32.4]
arr3 = np.array(data3)
print(arr1.dtype) #int32로 들어가는 구나
print(arr2.dtype)
print(arr3.dtype) #float64로 들어가는 구나
arr3

int32
int32
float64


array([ 1.  ,  2.53,  4.65, 32.4 ])

In [50]:
data4 = [1,2,3.0,4, 5]
arr4 = np.array(data4)
print(arr4.dtype)
arr4

float64


array([1., 2., 3., 4., 5.])

In [51]:
np.arrange(10)

AttributeError: module 'numpy' has no attribute 'arrange'

In [53]:
np.arange(10) #0에서부터 10 앞의 값까지 하는 것이구나.

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [54]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [55]:
np.arange(1,10,2) #step을 만들 수도 있을 것이다. 

array([1, 3, 5, 7, 9])

In [59]:
np.arange(1,10,2.1)

array([1. , 3.1, 5.2, 7.3, 9.4])

In [65]:
arr5 = np.arange(12).reshape(3,4)

In [69]:
print(arr1.shape)

(6,)


In [70]:
print(arr5.shape)

(3, 4)


In [73]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [74]:
np.ones((3,4,5)) #큰 범주, 행, 열 이렇게 되는듯

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [80]:
np.full((2,2),4) 

array([[4, 4],
       [4, 4]])

In [83]:
np.zeros((2,3,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [88]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

####  np.linspace

In [90]:
np.linspace(1,10,4) #균등하게 자르기. 1부터 10까지를 균등하게 네개로 잘랐을 때의 index

array([ 1.,  4.,  7., 10.])

#### type 바꾸기

In [92]:
data6 = ['1', '2', '3'] #문자를 이용해서 만들기. 
arr6 = np.array(data6)
arr6

array(['1', '2', '3'], dtype='<U1')

In [93]:
arr6.dtype

dtype('<U1')

In [94]:
arr6 = arr6.astype(int)
arr6

array([1, 2, 3])

In [115]:
data1 = [[1,2,3], [4,5,6], [7,8,9]]
arr7 = np.array([[1,2,3], [4,5,6], [7,8,9]])
arr7
arr7[1,2] #numpy로 만들어진 array는 이와 같이 불러올 수 있다는 장점을 가진다!!!!
arr7.astype(float)

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [117]:
b1 = np.arange(12).reshape(4,3)
b1

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [123]:
arr0 = np.ones(3)
arr0
arr0.astype(int)
arr_e = np.eye(5)
arr_e

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [141]:
#행렬의 한 행만 바꿀 수 있을까?
arr7 = np.array([['1','2','3'], [4,5,6], [7,8,9]]) #하나만 문자열이라도 나머지는 다 문자열로 바뀌게 된다. 
arr7
arr7.astype(int)

arr7[:3]

array([['1', '2', '3'],
       ['4', '5', '6'],
       ['7', '8', '9']], dtype='<U1')

In [143]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [145]:
np.arange(1,12,2, dtype = 'float').reshape(2,3)

array([[ 1.,  3.,  5.],
       [ 7.,  9., 11.]])

In [146]:
np.zeros((2,3,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [149]:
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

### random

#### rand

In [150]:
#0~1 사이의 값으로 ndarray생성 물론 랜덤이니 실행할때마다 값이 계속 달라진다. 


array([0.62001643, 0.54762901, 0.62357084, 0.32450385])

In [154]:
np.random.rand()

0.3489513100011673

In [155]:
np.random.rand(4)

array([0.62767421, 0.16496409, 0.64387786, 0.09597944])

In [156]:
np.random.rand(2,2)

array([[0.24616069, 0.34925583],
       [0.06050428, 0.81564343]])

In [157]:
np.random.rand(2,2,2)

array([[[0.8188089 , 0.07330781],
        [0.84920794, 0.08816308]],

       [[0.64662212, 0.23994455],
        [0.7518055 , 0.98500653]]])

In [158]:
np.random.randn(4) #정규분포의 랜덤 추출

array([1.50550869, 1.43532456, 1.52967295, 0.31883451])

In [163]:
#randint 특정 정수 사이에서 랜덤한 값을 추출한다. 
np.random.randint(1,100)

26

In [164]:
np.random.randint(1,100, size = (3))

array([28, 95, 74])

In [165]:
np.random.randint(1,100, size = (2,2))

array([[97, 20],
       [ 6, 59]])

In [166]:
np.random.randint(1,100, size = (2,2,2))

array([[[41, 55],
        [39,  3]],

       [[20,  1],
        [95, 50]]])

#### seed  랜덤한 값을 동일하게 계속 사용하고 싶을때

In [168]:
np.random.seed(1234)
np.random.randn(3,4)

array([[ 0.47143516, -1.19097569,  1.43270697, -0.3126519 ],
       [-0.72058873,  0.88716294,  0.85958841, -0.6365235 ],
       [ 0.01569637, -2.24268495,  1.15003572,  0.99194602]])

#### choice

In [179]:
#주어진 1차원 ndarray로부터 랜덤으로 샘플링을 진행. 중복추출이 가능한 점이 장점이다. 
sample_data = np.array([10,20,30,40,50])
np.random.seed(1234)
np.random.choice(sample_data, size = (4,4))

array([[40, 50, 50, 10],
       [20, 20, 20, 30],
       [40, 50, 50, 30],
       [30, 10, 10, 50]])

In [232]:
#choice - 정수가 주어지면 np.arange(정수)으로 간주함. 
np.random.choice(100,size = (7), replace = False)

array([35, 59, 73,  8, 85, 27, 68])

In [233]:
np.random.uniform(1,3,size = (4,5))

array([[2.53496582, 2.94317697, 2.50628965, 1.54832591, 1.20950237],
       [2.56513603, 2.95439521, 2.23770903, 1.96696277, 1.4427555 ],
       [2.15977268, 2.28319416, 2.86050425, 2.94639342, 1.48999909],
       [2.95481249, 1.23138881, 2.5609402 , 1.97279072, 2.61188011]])

In [235]:
np.random.normal(size = 100) #rnorm인가 그거랑 같네용

array([-0.27075205,  0.7831162 , -1.15167756,  1.27178484, -2.1527074 ,
        0.26123994,  0.81993786, -0.31277642,  0.2810808 , -0.4288255 ,
       -0.19151712, -0.69857269,  0.28619239,  0.57637719,  0.21085321,
       -2.02679571, -1.37119983,  0.93996847,  0.49043676,  0.56974424,
       -0.36140377,  1.80859012,  0.32837603, -0.49247685, -0.69040243,
        0.29713751,  1.03771865,  0.02660177,  0.44823619,  1.02491785,
       -0.46955534, -0.32337154, -0.08664273, -0.86242806,  1.15598616,
       -0.58364401, -1.41646053,  0.79919574, -2.06385626, -0.45767303,
        0.31579539, -0.01395932, -0.37606874, -0.71535621,  1.80275951,
       -1.53952602,  1.14438203,  0.13759794, -0.71026612, -0.47926292,
       -1.00097133,  0.44797868, -0.03864432, -0.46641198,  0.66833883,
        2.24315991, -0.19701979, -0.66773633, -0.59068348,  1.68843998,
        0.91539628,  0.75055314, -0.91473409, -0.60393701, -0.97889318,
        0.55966395,  0.05512862,  1.06374311, -1.91097918,  1.10

In [238]:
arr1 = np.array([10,20,30,40,50])
arr2 = np.array([1,2,3,4,5])
arr1 + arr2

array([11, 22, 33, 44, 55])

In [242]:
arr3 = np.arange(15).reshape(3,5) #메서드 체이닝
arr3

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [241]:
arr4 = np.random.rand(15).reshape(3,5)
arr4

array([[0.13160825, 0.41870524, 0.46054516, 0.37155112, 0.15608816],
       [0.45682374, 0.94228194, 0.76483598, 0.10815886, 0.16205581],
       [0.71798406, 0.51001133, 0.18620818, 0.32781835, 0.75108173]])

In [249]:
print(arr3 + arr4)
print('{0:-^70}'.format(''))
print(arr3 - arr4)
print('{0:-^70}'.format(''))
print(arr3 * arr4)
print('{0:-^70}'.format(''))
print(arr3 / arr4)
print('{0:-^70}'.format(''))

[[ 0.13160825  1.41870524  2.46054516  3.37155112  4.15608816]
 [ 5.45682374  6.94228194  7.76483598  8.10815886  9.16205581]
 [10.71798406 11.51001133 12.18620818 13.32781835 14.75108173]]
----------------------------------------------------------------------
[[-0.13160825  0.58129476  1.53945484  2.62844888  3.84391184]
 [ 4.54317626  5.05771806  6.23516402  7.89184114  8.83794419]
 [ 9.28201594 10.48998867 11.81379182 12.67218165 13.24891827]]
----------------------------------------------------------------------
[[ 0.          0.41870524  0.92109031  1.11465336  0.62435264]
 [ 2.28411871  5.65369162  5.35385188  0.8652709   1.45850226]
 [ 7.17984059  5.61012468  2.23449818  4.26163859 10.51514428]]
----------------------------------------------------------------------
[[ 0.          2.38831501  4.34267947  8.07425906 25.62654348]
 [10.94514039  6.36752098  9.15228906 73.96527474 55.53642412]
 [13.92788584 21.5681481  64.44399959 39.65610795 18.63978229]]
---------------------------

In [244]:
np.add(arr3, arr4) #이와 같은 메서드도 가지고 있다. 

array([[ 0.13160825,  1.41870524,  2.46054516,  3.37155112,  4.15608816],
       [ 5.45682374,  6.94228194,  7.76483598,  8.10815886,  9.16205581],
       [10.71798406, 11.51001133, 12.18620818, 13.32781835, 14.75108173]])

In [250]:
arr3 > arr4

array([[False,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [252]:
arr2**3

array([  1,   8,  27,  64, 125], dtype=int32)

In [253]:
arr2**4

array([  1,  16,  81, 256, 625], dtype=int32)

In [254]:
np.random.seed(1234)
np.random.randn(3,4)

array([[ 0.47143516, -1.19097569,  1.43270697, -0.3126519 ],
       [-0.72058873,  0.88716294,  0.85958841, -0.6365235 ],
       [ 0.01569637, -2.24268495,  1.15003572,  0.99194602]])

In [290]:
np.random.randn(3,4)


array([[ 1.22457436, -1.28110828,  0.8754755 , -1.71071532],
       [-0.4507651 ,  0.74916381, -0.20393287, -0.18217541],
       [ 0.680656  , -1.81849899,  0.04707164,  0.39484421]])

In [281]:
np.random.seed(1234)
np.random.randn(3,4)

array([[ 0.47143516, -1.19097569,  1.43270697, -0.3126519 ],
       [-0.72058873,  0.88716294,  0.85958841, -0.6365235 ],
       [ 0.01569637, -2.24268495,  1.15003572,  0.99194602]])

In [293]:
print(arr1)
arr1 + 2

[10 20 30 40 50]


12

In [294]:
arr1 > 20

array([False, False,  True,  True,  True])

### 통계함수

In [297]:
print(arr1)
print(np.mean(arr1))
print(np.var(arr1))

[10 20 30 40 50]
30.0
200.0


In [298]:
arr1.mean()

30.0

In [299]:
np.max(arr1)

50

In [300]:
np.min(arr1)

10

In [304]:
print(np.median(arr1), np.std(arr1))

30.0 14.142135623730951


### 집계함수

In [305]:
np.sum(arr1)

150

In [307]:
print(np.cumsum(arr1))
arr1.cumsum()

[ 10  30  60 100 150]


array([ 10,  30,  60, 100, 150], dtype=int32)

In [309]:
print(np.cumprod(arr1))

[      10      200     6000   240000 12000000]


#### any, all 연산자

In [311]:
#any : 특정 조건을 만족하는 것이 하나라도 존재하면 True, 아니면 False
#all : 모든 원소가 조건에 만족해야만 True. 하나라도 만족하지 않는다면 False
arr5 = np.random.randn(10)
print(arr5)

[-0.24843205 -0.61770665 -0.682884    0.4362576  -1.70301277  0.3937106
 -0.479324   -0.29901629  0.69410329  0.67862967]


In [312]:
arr5 > 0

array([False, False, False,  True, False,  True, False, False,  True,
        True])

In [313]:
np.any(arr5 > 0)

True

In [315]:
np.all(arr5 > 0)

False

#### where 함수

In [317]:
# where 함수
#조건에 따라서 선별적으로 값을 선택. SQL의 where 절과 비슷하다.
np.where(arr5 > 0, arr5, 0)

array([0.        , 0.        , 0.        , 0.4362576 , 0.        ,
       0.3937106 , 0.        , 0.        , 0.69410329, 0.67862967])

In [318]:
myarr = np.array(['김밥', '돈까스', '냉면'])
np.where(myarr =='김밥', myarr, '탈락')

array(['김밥', '탈락', '탈락'], dtype='<U3')

In [320]:
myarr[myarr =='김밥']

array(['김밥'], dtype='<U3')

### 행렬연산

In [329]:
a = np.array([0,1,2,3,7,6]).reshape(2,3)
a

array([[0, 1, 2],
       [3, 7, 6]])

In [328]:
b = np.array([3,2,0,1,3,2]).reshape(3,2)
b

array([[3, 2],
       [0, 1],
       [3, 2]])

In [330]:
a.dot(b)

array([[ 6,  5],
       [27, 25]])

In [331]:
np.dot(a,b)

array([[ 6,  5],
       [27, 25]])

In [332]:
np.dot(b,a)

array([[ 6, 17, 18],
       [ 3,  7,  6],
       [ 6, 17, 18]])

In [333]:
np.transpose(a)

array([[0, 3],
       [1, 7],
       [2, 6]])

In [363]:
np.transpose(b)

array([[3, 0, 3],
       [2, 1, 2]])

In [368]:
#역행렬 구하기
c = np.arange(4).reshape(2,2)
print(c)
np.linalg.inv(c)
np.dot(c, np.linalg.inv(c))

[[0 1]
 [2 3]]


array([[1., 0.],
       [0., 1.]])

In [369]:
#determinant 구하기 - linalg가 linear algebra 인건가?

np.linalg.det(c)

-2.0

### 인덱싱

In [335]:
#1차원 벡터의 인덱싱
arr1 = np.arange(10)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [336]:
arr1[3]

3

In [338]:
arr1[3] = 100
arr1

array([  0,   1,   2, 100,   4,   5,   6,   7,   8,   9])

In [339]:
#2차원 행렬의 인덱싱
arr2 = np.arange(10).reshape(2,5)
arr2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [344]:
#인덱스를 ,로 구분해서 접근한다. 
arr2[1,2]

IndexError: index 7 is out of bounds for axis 0 with size 2

In [362]:
arr2[7] #이렇게 하면 도출되지 않는다. 아예 행렬 느낌으로 가는 것 인듯. R에서 처럼 (2,2) 이렇게 행과 열을 잘 구분해줘야 하는듯 하다.

IndexError: index 7 is out of bounds for axis 0 with size 2

In [356]:
arr3 = np.arange(24).reshape(2,3,4)
print(arr3)
arr3[0,2,2]
                        

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


10

In [357]:
arr3[0,0,-1]

3

In [358]:
arr3[0]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [359]:
arr3[0,0]

array([0, 1, 2, 3])

In [360]:
arr3

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [361]:
arr3[1,2,3]

23

In [370]:
arr5 = np.arange(10,100,10).reshape(3,3)
arr5

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [371]:
arr5[0,2]

30

In [373]:
arr5[2,2] = 95
arr5

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 95]])

In [376]:
arr5[2]

array([70, 80, 95])

In [377]:
arr5[0] = np.array([0,0,0])
arr5

array([[ 0,  0,  0],
       [40, 50, 60],
       [70, 80, 95]])

In [378]:
arr5[3] = np.array([0,0,0])

IndexError: index 3 is out of bounds for axis 0 with size 3

#### 인덱스에 조건 넣기

In [379]:
arr6 = np.array([1,2,3,4,5,6])
arr6[arr6 > 3]

array([4, 5, 6])

In [380]:
arr6[(arr6 % 2) == 0] #짝수만 보여주세요.

array([2, 4, 6])

### 슬라이싱

In [381]:
arr7 = np.arange(10)
arr7

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [382]:
arr7[1:]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [384]:
arr7[3:6]

array([3, 4, 5])

In [385]:
arr7[2:-3]

array([2, 3, 4, 5, 6])

#### 2차원 배열 슬라이싱

In [386]:
arr8 = np.arange(10).reshape(2,5)
arr8

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [388]:
arr8[:,:2]

array([[0, 1],
       [5, 6]])

In [389]:
arr8[:,2:4]

array([[2, 3],
       [7, 8]])

In [390]:
arr9 = np.arange(36).reshape(6,6)
arr9

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [396]:
arr9[[1,4],[3,5]] #R처럼 원하는 부분만 뽑아낼 수는 없을까?

array([ 9, 29])

In [397]:
arr11 = np.arange(15).reshape(3,5)
arr11

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

#### ravel - ndarray의 shape을 변경하는 방법

In [401]:
#다시 펼치기
print(arr11)
np.ravel(arr11, order = 'C')

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [403]:
#이건 이제 column을 기준으로 펼쳐주는 것. Parameter로 C(row가 우선), F(column이 우선)
np.ravel(arr11,order ='F') 

array([ 0,  5, 10,  1,  6, 11,  2,  7, 12,  3,  8, 13,  4,  9, 14])

In [404]:
temp = np.ravel(arr11)
temp[0] = 100
print(temp)
print(arr11) #원본 데이터가 바뀐다. 

[100   1   2   3   4   5   6   7   8   9  10  11  12  13  14]
[[100   1   2   3   4]
 [  5   6   7   8   9]
 [ 10  11  12  13  14]]


#### flatten - 원본 데이터가 바뀌지 않는다.

In [406]:
arr12 = np.arange(15).reshape(3,5)

temp2 = arr12.flatten()
temp2[0] = 100
print(temp2)
print(arr12) #원본 데이터가 바뀌지 않는다. 

[100   1   2   3   4   5   6   7   8   9  10  11  12  13  14]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [410]:
arr12.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [413]:
arr12[1][1:4]

array([6, 7, 8])

#### axis

In [417]:
a1 = np.arange(15)
a1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [419]:
np.sum(a1, axis = 0)

105

In [420]:
np.sum(a1, axis = 1) #1차원은 기본적으로 0이다. 

AxisError: axis 1 is out of bounds for array of dimension 1

In [422]:
a2 = a1.reshape(3,5)
a2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [424]:
np.sum(a2)

105

In [425]:
np.sum(a2, axis = 0) #열이 중심이 되어서 결과값을 낸다. 

array([15, 18, 21, 24, 27])

In [426]:
np.sum(a2, axis = 1) #행이 중심이 되어서 결과값을 낸다. 

array([10, 35, 60])

R과는 정 반대다. R의 apply(,1,)은 행을 중심으로, apply(,2,)는 열을 중심으로 하는데 여기는 먼저 나오는 것이 열이 중심이 된다.

In [428]:
a3 = np.arange(20).reshape(2,2,5)
a3

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]])

In [429]:
print(np.sum(a3))
print(np.sum(a3, axis = 0))
print(np.sum(a3, axis = 1))
print(np.sum(a3, axis = 2))


190
[[10 12 14 16 18]
 [20 22 24 26 28]]
[[ 5  7  9 11 13]
 [25 27 29 31 33]]
[[10 35]
 [60 85]]


#### 브로드캐스팅

In [ ]:
a = np.arange(12).reshape(4,3)
b = np.arange(100,103)
c = np.arange(100)

- dtype을 지정해서 ndarray를 만들 수 있을 것이다. numpy의 핵심은 배열 형태로 저장을 해준다는 것을 알아야 한다. 리스트에 들어있을 때랑 배열에 들어있을때 속도가 다르다. 
- call by reference : 변할 수 있는 애들은 전달해줄때. 함수에 있는 데이터를 바꿀 때 실제 데이터도 바뀌어 버리는 것을 알 수 있을 것이다. 이건 왜냐면 리스트의 주소를 복사하는 것이기 때문이다. 
- 어떤 언어든 random이라는 함수는 존재한다. 다양하게 랜덤 값을 생성할 수 있었을 것이다. 
- seed() : 시드를 지정해서 항상 같은 값을 뽑아낼 수 있게 한다. 
- 통계함수 : 
- 인덱싱과 슬라이싱 : 차원이 깊어질 경우 행과 열을 기준으로 뽑아주는 것이다. 인덱싱을 하게 되면 차원이 하나 줄게 된다. 그러나 슬라이싱을 할 경우에 차원이 줄어들지는 않는다. 
- arange해서 reshape : reshape할땐 원소의 개수와 shape을 잘 파악해야 한다. 
- axis의 경우는 계속해서 나오니 정리해두는 편이 좋다. 
- np.ones(), np.zeros() : 0과 1로 채우는 것들. 아마 이걸 넣고 채우는 것도 편할 것 같다. 
- copy.deepcopy

#### call by value와 call by reference
물이 한잔 있다고 할때 물을 한잔 더 따르는 것과 물을 다른 컵에 따르는 것. 이게 value와 reference. R은 아마 call by value를 따르고 Python은 call by reference를 따르는 것 같다. 실제로 하나를 복사했다고 한다면 이건 주소를 복사하는 것이기 때문에 바꿀 때, 그 값도 같이 바뀐다. 