## 01. 배열 데이터를 효과적으로 다루는 numpy

### 배열 생성하기

#### 시퀀스 데이터로부터 배열 생성

In [1]:
import numpy as np

In [2]:
data1 = [0,1,2,3,4,5]
a1 = np.array(data1)
a1

array([0, 1, 2, 3, 4, 5])

In [3]:
data2 = [0.1, 5,4,12, 0.5]
a2 = np.array(data2)
a2

array([ 0.1,  5. ,  4. , 12. ,  0.5])

In [4]:
print(a1.dtype)
print(a2.dtype)

int32
float64


In [5]:
np.array([0.5, 2, 0.01,8 ])

array([0.5 , 2.  , 0.01, 8.  ])

In [6]:
np.array([[1,2,3], [4,5,6], [7,8,9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

#### 범위를 지정해 배열 생성

- np.arange()라는 함수를 이용해 생성한다. np.arange([start,] stop[, step])
- start에서 시작해서 stop 전까지!

In [8]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [9]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

- reshape(n,m)을 추가하면 행렬꼴로 만들어준다

In [11]:
np.arange(12).reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [12]:
b2 = np.arange(5)
b2.shape

(5,)

- linspce(start, stop, num)
- 시작과 끝을 지정하고 데이터의 개수를 정한다
- 여기서는 range와는 다르게 맨 끝 값까지 포함하는 듯 싶다

In [18]:
np.linspace(1,10,4)

array([ 1.,  4.,  7., 10.])

In [20]:
np.linspace(1,10,8)
#이렇게 1부터 10을 8개의 등구간으로 나눌 값을 찾아준다. 생각보다 편리할 것 같다

array([ 1.        ,  2.28571429,  3.57142857,  4.85714286,  6.14285714,
        7.42857143,  8.71428571, 10.        ])

####  특별한 형태의 배열생성

In [22]:
np.zeros(3)

array([0., 0., 0.])

In [23]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [24]:
np.ones(3)

array([1., 1., 1.])

In [25]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

- 단위행렬을 만들어주는 np.eye함수

In [26]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 배열의 데이터 타입 변환

In [29]:
str_a1 = np.array(['1.24', '232', '5.53'])
num_a1 = str_a1.astype(float)
num_a1

array([  1.24, 232.  ,   5.53])

In [30]:
print(str_a1.dtype)
print(num_a1.dtype)

<U4
float64


#### 난수 배열의 생성

- np.random.rand([d0, d1,   ..., dn])
0과 1사이의 난수 생성! (2,3)이라면 2차원 행렬로 나타남
- np.random.randint([low,] high [,size])

In [32]:
np.random.rand(2,2,2)

array([[[0.73250468, 0.28235838],
        [0.57269216, 0.85594065]],

       [[0.65589341, 0.48601062],
        [0.36867494, 0.77560647]]])

In [40]:
np.random.randint(1,10,2) #1부터 10사이 숫자 중 2개를 랜덤하게 추출

array([7, 7])

### 배열의 연산

#### 기본 연산

In [41]:
arr1 = np.array([1,2,3])
arr2 = np.array([10,20,30])

In [42]:
arr1 **2

array([1, 4, 9], dtype=int32)

In [43]:
arr1 * arr2

array([10, 40, 90])

#### 통계를 위한 연산

- 합, 평균, 표준편차, 분산, 최솟값과 최댓값, 누적 합과 누적 곱 등 통계에서 많이 사용하는 매서드 존재

In [44]:
arr3 = np.arange(5)

In [45]:
[arr3.sum(), arr3.mean()]

[10, 2.0]

#### 행렬연산

In [47]:
A = np.array([0,1,2,3]).reshape(2,2)
A

array([[0, 1],
       [2, 3]])

In [49]:
B = np.array([3,2,0,1]).reshape(2,2)
B

array([[3, 2],
       [0, 1]])

- 행렬곱은 dot이라는 함수를 활용한다

In [50]:
A.dot(B)

array([[0, 1],
       [6, 7]])

In [51]:
np.dot(A,B)

array([[0, 1],
       [6, 7]])

In [52]:
np.transpose(A)

array([[0, 2],
       [1, 3]])

In [53]:
np.linalg.inv(A) #역행렬 구하기

array([[-1.5,  0.5],
       [ 1. ,  0. ]])

In [54]:
np.linalg.det(A) #determinant를 구하는 것 같다

-2.0

### 배열의 인덱싱과 슬라이싱

#### 배열의 인덱싱

In [55]:
a1 = np.array([0,10,20,30,40,50])
a1

array([ 0, 10, 20, 30, 40, 50])

In [56]:
a1[0]

0

In [57]:
a1[4]

40

원소도 변경할 수 있다

In [58]:
a1[5]=70
a1

array([ 0, 10, 20, 30, 40, 70])

여러개의 원소를 선택하려면 아래와 같이

In [59]:
a1[[1,3,4]]

array([10, 30, 40])

In [60]:
a2 = np.arange(10,100,10).reshape(3,3)
a2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [61]:
a2[0,2]

30

In [62]:
a2[2,2]

90

In [63]:
a2[1]

array([40, 50, 60])

- 2차원 배열의 여러원소 선택하기

In [65]:
a2[[0,2], [0,1]]#R에서는 (0,0) (2,1)을 가져오는 것과 같다

array([10, 80])

#### 배열의 슬라이싱

- 반환되는 원소의 범위는 **시작위치 ~ 끝위치-1 이다**

In [66]:
b1 = np.array([10,20,30,40,50])
b1[1:4]

array([20, 30, 40])

- 2차원 행렬에서는 [행시작위치:행끝위치], [열시작위치 : 열끝위치]로 진행한다.
- 특정 행을 선택한 후 열을 슬라이싱하려면 [행위치],[열시작위치:열끝위치] 로 진행함

In [68]:
b2 = np.arange(10,100,10).reshape(3,3)
b2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [69]:
b2[1:3,1:3]

array([[50, 60],
       [80, 90]])

In [71]:
b2[1][0:2]

array([40, 50])