In [2]:
#1. 0으로 채워진 크기가 20인 배열을 생성하세요.
import numpy as np
a1 = np.zeros(20)
a1

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

In [5]:
#2. 0부터 15까지의 값을 갖는 4 x 4 행렬을 생성하세요.
a2 = np.arange(16).reshape(4,4)
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [6]:
#3. 길이가 10인데 세번째 요소만 1이고, 나머지 요소는 0인 배열을 생성하세요.
a3 = np.zeros(10)
a3[2] = 1
a3

array([0., 0., 1., 0., 0., 0., 0., 0., 0., 0.])

In [8]:
#4. 1에서 10까지의 값을 갖는 배열을 생성하세요.
a4 = np.arange(1,11)
a4

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [18]:
#5. 위의 배열의 순서를 거꾸로 바꿔주세요.
a5 = a4[::-1]
a5

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [20]:
#6 4x4 단위행렬을 만드세요. (단위 행렬(영어: identity matrix)은 주대각선의 원소가 모두 1이며 나머지 원소는 모두 0인 정사각 행렬이다.)
a6 = np.eye(4)
a6

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [24]:
#7 랜덤한 값을 가지는 3X3X3 배열을 생성하세요.
np.random.seed(1234)
a7 = np.random.randint(100, size = (3,3,3))
a7

array([[[47, 83, 38],
        [53, 76, 24],
        [15, 49, 23]],

       [[26, 30, 43],
        [30, 26, 58],
        [92, 69, 80]],

       [[73, 47, 50],
        [76, 37, 34],
        [38, 67, 11]]])

In [59]:
#8. 위에서 생성한 배열 원소의 최대값, 최솟값을 구하세요.
print('최대값: {0}'.format(np.max(a7)))
print('최대값: {0}'.format(np.min(a7)))

최대값: 92
최대값: 11


In [31]:
#9. 20개의 랜덤한 값을 가진 배열을 생성하고, 그 배열의 평균값을 구하시오. 참고: numpy에서 평균을 구하는 함수 - mean()
np.random.seed(1234)
a9 = np.random.randint(100,size = (20))
print(a9)
a9.mean()

[47 83 38 53 76 24 15 49 23 26 30 43 30 26 58 92 69 80 73 47]


49.1

In [55]:
#10. 4x4 의 2차원 배열을 생성하세요. 단 테두리는 1을 내부는 0으로 채워주세요.
a10 = np.zeros((4,4))
for i in [0,3]:
    for j in range(4):
        a10[i,j] = 1
        a10[j,i] = 1
print(a10)

[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]
